### ISSUE TITLE
Project seems stagnant..

### ISSUE THREAD

**Issue by dkwl93** [morgsmccauley/jim#1]
Will there be any updates made to this project? Eagerly waiting the new version

From Jims biggest fan...

**Comment by morgsmccauley** [comment]
Jim is now deprecated and will be replaced with [reddit-clone](https://github.com/morgsmccauley/reddit-clone)

**Comment by dkwl93** [comment]
Wow. Although I am very disappointed, I respect OP's decision... How will reddit-clone help me shred for RnV?

**Comment by morgsmccauley** [comment]
I recommend giving up on that goal and instead live vicariously through people on r/shredded using [reddit-clone](https://github.com/morgsmccauley/reddit-clone)
